version: '3'

networks:
  nginx-php74-symfony:

services:
  #Serveur HTTP
  http:
    container_name: http
    image: nginx:latest
    ports: 
      - "8080:80"
    links: 
      - php74-service
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - nginx-php74-symfony

  mysql8-service:
    container_name: sql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nginx-php74-symfony
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nginx-php74-symfony
      
  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - nginx-php74-symfony

  phpmyadmin-service:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql8-service
    links:
      - mysql8-service
    restart: always
    ports:
      - "5501:80"
    volumes:
      - ./phpmyadmin:/var/www/phpmyadmin
    environment:
        #PMA_ARBITRARY: 1
        PMA_HOST: mysql8-service
        PMA_USER: root
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nginx-php74-symfony


